"""add role to customer

Revision ID: 1d4ea09a40b5
Revises: 7cf5f5cb9618
Create Date: 2025-06-22 00:19:49.064047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4ea09a40b5'
down_revision: Union[str, None] = '7cf5f5cb9618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'role')
    # ### end Alembic commands ###
